apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
spec:
  project: default
  source:
    chart: kibana
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    helm:
      releaseName: kibana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging
  syncPolicy:
     automated:
       prune: true
       selfHeal: true
     syncOptions:
      - CreateNamespace=true